Added safety for internal cache system. Was producing errors randomly involving null keys in the HashMap.
```
[ServerPatches] Unhandled exception occurred in onPacketReceiving(PacketEvent) for ServerPatches
   java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.HashMap.get(Object)" is null
           at Summiner.ServerPatches.Listeners.Spigot.TasksPerMinute.addExecution(TasksPerMinute.java:30) ~[Server-Patches-0.0.5.jar:?]
           at Summiner.ServerPatches.Listeners.Spigot.Manager.PacketEvent(Manager.java:64) ~[Server-Patches-0.0.5.jar:?]
           at Summiner.ServerPatches.Listeners.Spigot.Manager$1.onPacketReceiving(Manager.java:43) ~[Server-Patches-0.0.5.jar:?]
```